# Generated by Django 5.1.3 on 2024-11-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='api.post',
        ),
    ]
